/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Spark的个人博客",
  "description": "Spark's blog",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "tdfgbg f d",
      "frontmatter": {
        "description": " ..."
      },
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-79bbaf99",
      "path": "/guide/",
      "summary": " ..."
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You",
        "description": "::: slot footer\nMIT Licensed | Copyright © 2018-present Evan You\n::: ..."
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-39f53506",
      "path": "/",
      "summary": "::: slot footer\nMIT Licensed | Copyright © 2018-present Evan You\n::: ..."
    },
    {
      "title": "Hello World",
      "frontmatter": {
        "title": "Hello World",
        "date": "2020-01-11T00:00:00.000Z",
        "author": "Billyyyyy3320",
        "location": "Taipei",
        "description": "This is official blog theme.\nMy content. ..."
      },
      "regularPath": "/posts/2021-6-1-one.html",
      "relativePath": "posts/2021-6-1-one.md",
      "key": "v-7d117ef6",
      "path": "/posts/2021-6-1-one.html",
      "summary": "This is official blog theme.\nMy content. ..."
    },
    {
      "title": "前端基础",
      "frontmatter": {
        "description": "学习资源\nMDN\nw3school\n练习空间\nfreeCodeCamp\n[freeCodeCamp 中文社区](https://www ..."
      },
      "regularPath": "/posts/front-end-basic/",
      "relativePath": "posts/front-end-basic/README.md",
      "key": "v-16c8bff4",
      "path": "/posts/front-end-basic/",
      "headers": [
        {
          "level": 2,
          "title": "学习资源",
          "slug": "学习资源"
        },
        {
          "level": 2,
          "title": "练习空间",
          "slug": "练习空间"
        },
        {
          "level": 2,
          "title": "团队空间",
          "slug": "团队空间"
        },
        {
          "level": 2,
          "title": "博客资源",
          "slug": "博客资源"
        }
      ],
      "summary": "学习资源\nMDN\nw3school\n练习空间\nfreeCodeCamp\n[freeCodeCamp 中文社区](https://www ..."
    },
    {
      "frontmatter": {
        "description": "start ..."
      },
      "regularPath": "/posts/front-end-basic/start/start-1.html",
      "relativePath": "posts/front-end-basic/start/start-1.md",
      "key": "v-98790aa4",
      "path": "/posts/front-end-basic/start/start-1.html",
      "summary": "start ..."
    },
    {
      "title": "Vue 学习",
      "frontmatter": {
        "description": "官方资源\nVue.js 官方文档\n周边工具\nVue Cli 脚手架\nvue-devtools\n[Vue Router](https:/ ..."
      },
      "regularPath": "/posts/vue/",
      "relativePath": "posts/vue/README.md",
      "key": "v-738398aa",
      "path": "/posts/vue/",
      "headers": [
        {
          "level": 2,
          "title": "官方资源",
          "slug": "官方资源"
        },
        {
          "level": 2,
          "title": "周边工具",
          "slug": "周边工具"
        }
      ],
      "summary": "官方资源\nVue.js 官方文档\n周边工具\nVue Cli 脚手架\nvue-devtools\n[Vue Router](https:/ ..."
    },
    {
      "frontmatter": {},
      "regularPath": "/posts/two.html",
      "relativePath": "posts/two.md",
      "key": "v-59aabfc8",
      "path": "/posts/two.html"
    },
    {
      "title": "vue2",
      "frontmatter": {
        "description": " ..."
      },
      "regularPath": "/posts/vue/vue2/1.html",
      "relativePath": "posts/vue/vue2/1.md",
      "key": "v-27c1e9ae",
      "path": "/posts/vue/vue2/1.html",
      "summary": " ..."
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Tag"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    }
  ],
  "themeConfig": {
    "docsDir": "docs",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端领域",
        "link": "/posts/front-end-basic/"
      },
      {
        "text": "Vue学习",
        "link": "/posts/vue/"
      },
      {
        "text": "Angular学习",
        "link": "/posts/angular/"
      },
      {
        "text": "小程序学习",
        "link": "/posts/wxapp/"
      },
      {
        "text": "暂未分类",
        "link": "/posts/others/"
      },
      {
        "text": "前端进击",
        "link": "/posts/front-end-hit/"
      },
      {
        "text": "全栈之路",
        "link": "/posts/full-stack/"
      },
      {
        "text": "Github",
        "link": "https://github.com/zty1999"
      },
      {
        "text": "FAQ记录",
        "link": "/faq"
      }
    ],
    "sidebar": {
      "/front-end-basic/": [
        {
          "title": "前端入门",
          "collapsable": true,
          "children": [
            "/front-end-basic/start/start-1.md"
          ]
        }
      ],
      "/vue/": [
        {
          "title": "深入理解Vue.js与实战",
          "path": "/vue/vue2/1.md"
        },
        {
          "title": "深入理解 Vue 动画效果",
          "collapsable": true,
          "children": [
            "/vue/vue-transition/1-transition-component.md",
            "/vue/vue-transition/2-css-transition-animation.md",
            "/vue/vue-transition/3-javascript-hook.md",
            "/vue/vue-transition/4-multi-element.md",
            "/vue/vue-transition/5-list-and-flip.md"
          ]
        },
        {
          "title": "Webpack 实现 Vue 多页应用",
          "collapsable": true,
          "children": [
            "/vue/vue-multi-page/1-init-project.md",
            "/vue/vue-multi-page/2-page-utils.md",
            "/vue/vue-multi-page/3-node-packages.md",
            "/vue/vue-multi-page/4-build.md",
            "/vue/vue-multi-page/5-dev-server.md",
            "/vue/vue-multi-page/6-hot-reload.md",
            "/vue/vue-multi-page/7-source-map-and-uglifyjs.md",
            "/vue/vue-multi-page/8-certain-loaders.md"
          ]
        }
      ]
    },
    "summary": true,
    "summaryLength": 200,
    "pwa": false
  }
}